#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

AppIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAtJJ"
    "REFUWIXNl81O20AQx38JMUoQRdBEPXGCAyDgBgqROHCFQ6tKSCnnSDxB4SXa96A9tk8RjlCS"
    "EBBWsIxUidBEsfOJle0h9sqOEyClxf1L1n7M7sx4/rOzNgSMkN2KF7b7ym5b4Rc27EPEPSgU"
    "Cr4FqqoyNzc3cPMwmaqqAD7Z6ekp6XT6J/DanvoVoQ/1et0zbjabvrnHZM1mc6AuG2+ACbtf"
    "8znwAgjjinzgORC4Ax4KVFWV/LlRKpWGKhhFdnNz87ADOzs7GIYxVOFzMeiUBU5B4A44EIAQ"
    "QoharSa2t/bF9ta+7Dvyf/F47gIhxMAcmJqawpH/DeRyOQBWVlaCp2BgJUy//QjA1++fZR/g"
    "5OSEeDzOxESvksZiMWKxmDy6pmlSrVZlFFutFkIIWZJN06TT6aBpmtT5JAqc45NMJsnlcsTj"
    "cY8DDgzD8DlQr9cxTROAdrtNqVTi8PDQ2ZIaKQKb67ssLy9TLBYBUBQFy7KIRqMAhMNeRrvd"
    "Lu12m06nA+A2/t5ech54DjyJAjcKhQLJZBKAq6srEokE4+PjADQaDcrlsswJwzCoVCoyYgcH"
    "B46aVbvVR6LAweb6LgDz8/Nomsb09DQAY2NjANzf38v2+vpaGj46OmJvb+95EXDDiYau6wBM"
    "Tk5SLpe5u7sD4OzsjEwmw/HxsdxjR09GIPAc8FEghODDu17Ivnz7JPvDsLm+y+zsLAC6rqMo"
    "ivwmzGQyZLNZFhcXAcjn8779PgpqtdrIb+HUiY2NDYrFIgsLCwBks1mWlpbkunw+TyqVgseS"
    "cFS4jTgJ2D8P/joB/8F17IlAtVpF0zRCoR4zlmURiURkJVMUhVAohGVZvc22TFEUqcN9Y15e"
    "XnqM3d7ePuzAzMzMs96m34G1tbVBS7r243HA+VdL0Ptp+FNqflxcXLjHqwPWdIGG3bcCzwHn"
    "GDqRiDLkG+GJqPSNh3Fq2W3rN99hfIvoJi2VAAAAAElFTkSuQmCC")
getAppIconData = AppIcon.GetData
getAppIconImage = AppIcon.GetImage
getAppIconBitmap = AppIcon.GetBitmap

