#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

DzpkIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACbVJ"
    "REFUWIWtl3usHddVxn9rz5w5595zH77Xz1zHj9hOnDixY8dgqqapb0JRoCEoRSmixBSKVAu1"
    "DQ+BEBRoi9QCLUmhRIRWrqAJVlJISi2qOG2c1kld7Lqyk9aPNA4Oduxc2/HrPs85M7P3Xos/"
    "zjnXaaDwD1ta2rNnNLPW+va3vrVH6Iw777yTw4cPrz106NC7tm3bdkdRFM7MRET4v4aZkRcF"
    "RVHw2JJVGEbqEhIR0iSh6lKr1jL93Ec+vPvpTbc/e7o3P/T4zqcBEIDVq1cv27p1619s3779"
    "fapKkiTth29x/ta1maGqhBBoTU+zZWCYtT29uI7jRBKcOCpOEARnRsUl/P599/3LF7/w+B/e"
    "eOCpE4mZMTMz89c7d+7c4r2XNE1J05QkSXDO4ZwjSZLZdfe6uzYzQoyscymjA4M4EZwTEkkQ"
    "5xBxJM7hEkciDsN478kTa/74l98z/PLXvrpD9uzZs/T+++9/zczIsgwRmc30x80AMUZCCCxs"
    "5by7d5AhVXprGaaGiJB2nYvrICGkrv3+YlWqIpzfvXt5euDAgfXeeyqVyo9A+2bYzey/zd57"
    "iqLgl/oG6QnQDJE+EwIRU0EBJ6AOxAARIg4nkJshMfD4ti/ekpw7d+7eGOMdb4b0xw0RQVXx"
    "3rMkL9haH4RWSaMsaeQewxjOehhIa6QiOAA1UoEKQl2EPoQeDB8iv/79o8dS732iqnTtf2N9"
    "N/O8KPiF3n5q0ZgIER8i0XumppW+LKEVSgbSjGriSHBk4qiIMCdxCEZRBtSUcxqzNIQg3cy6"
    "AbyZB13Yu/vebDS4I82oFp5pH8kLjzl47xMfIxPhyS2fhDLQHKzjxOEA6VTBvDTDiaAxEmNA"
    "BUm7Ts1s1t4cRNe5qhFj5Go13lap4vMSH5R6PeP1UDJvZD5mys98eiuv7PwuJ3cdIBVHNavQ"
    "U8tw4pgKnlQcFgNBlYqLdAJoZ9d2CCKuM3dRgBA8eVHyB1kfvpFTzxLqWcbRsmDk2qVYVDBj"
    "8c3XsvjmVbg/2dLWiLLkpR37mbNsiMvHz9Aan+LiqSlmLk0w3sxJu9l1s29rU3tWVczambda"
    "LawsiVbBTEnMcdaXpFGZMzJ8hai0vxO9AkZoea5/90ayesayt13fDrSymBAcqfSRqgbM5C0I"
    "tDP33pMkCQ888CAbVl1DdXg+VTMcoCKEEHhk408xt5KAtcMG105AIJYeVUinpjh/fIKvfv8V"
    "7rv3dvqHMiqZsOi65ZaqAp2or/BBAWi1ctI0ZfGSpQyMvULfdWs64t2pCqAWlPzyNCQpaAS0"
    "HYgJrpJSy1J2feu7bH9qF3/2id+jXssQl2LRAy2cakA1zloIgRA8K1euZMdj/8TRI0e4+frr"
    "COMXCJff+J/EgbN7jzB+/BTNS5PgUsQl4BLEpTRyz7qfXs+2z/wcy0aGoTIPizkaWxAmSFVB"
    "pE00M1BV1q5bx8Mf+yPmjJ+hp1pFm9NURpajM1Mwd+Fs9h2dQZs5/QMJZiUWIpIm7Y+JoVRZ"
    "NHcFsRgCcbi0jkYP5kGLjlipziJgphw8eID9J8fIx14jP30cjZHJf/g0Vraw9p61HQBBAz2V"
    "hA/+4p/y6LM/5AfPPYqWDcw5TBL66ykaG0hSwaV1zCKqTWJoEPwkLoTQqYArKBR5wdPfeIZk"
    "7gLyIweQag99d91HunAJk1/6DK0Du5n5ty9heYuoCii35YG39ws33LyGWPhONbVNaJPbEEw9"
    "piVqnnLibLsM2wSMdFU4yyrs+Ncn+csNi2l8eye9N26k/54P0Nj1FVr7nqG17xmIgWTeVaSm"
    "TPlAEQJnXjzK0vV3Yc7jDFyadgjeblBt2D2mObGYxoVoswGYQYiKE+logBFG76Gmgkj7gJJd"
    "vwHzJZKkJMMLqaxcQ1+a8IYqgvDqvqO8fevd+JkpyiKQtAyZbpLMqdOcmmbgphWoRjCjOH8a"
    "li5vc6ArNh9Oe5jf2eNqNeNvHnmM3vf/Dm7JCjCjsmQF1Z+8g9ho0P/RjyND/ZwqSlpqFMD4"
    "mct87cEvUxaBg7/7dzz/xPf45hN72f3Bv0Knm2ABEWXypb1IzEGDuW41RTPWiWMgXlHE5557"
    "jvPnz1/pkGb037WF6qZbyfqWkFaHcP011IzCDAVeeGo/j3z08yz51c2E/f/O1d95gVvftZ6B"
    "W1a2qyYGLORU+gdxCEm9Xh8FGzVgY4zcmmY81WpQhMDZM2M0L1zgttFRWnlOnufE1FNds5iX"
    "nj/Gnoce4vTBQ21VxIhAEJi4OM2eb+xHVi1k06fez/B7bifJUppnXqV58jC1+YtIajU+O7d3"
    "j+squBPhdY1c9CW/kmTcLgm/0TvAphePMHHiBHlZUoSA5WfBlBce28YLT/4zZYgU3hNVMQxF"
    "UIwkSTm274ds/+SjFHnBq4eO03rjNRBIaz2zgioLFiz4uIh8wjmhLErmR+VDPX1c7VKaplwM"
    "Jb1XLSIVoXH6dd73zc9SmzfSLi/nEOcwEsaOnuNbDz9K3yJjyY3LOHH4FD94/ggXXrtANIgY"
    "n9vxEYIP9I1cg2lg5No5f57U6/VRERkVcRQhUDXY0tOPAZdjoBSIMzPoTIPLBlPjZ1lwdT/V"
    "4YVt3YgBDZ6hkblct/kdrN4wyMiKEdZsWs3ad9wAGMePnGJoQT/v/Pn1II6sfxBQHhyu7Umd"
    "czHGSNDI3/cOsdQ5JjQC0LROWYrj1aJgMkYu7XiRPV85yPK1I9yyeQ1r79lMWp8DFsiyjDiT"
    "EC3gxBiaN8C9v303i85McMOHbsPMcGkFrN2qTVyZJkkyXXpP1YwNScLFWam9ovcCXIyRHgEF"
    "cI7pl95g37HznPmPc9x010ZWjN7Z6YYGaOdlw6Iyb7ifik8hixjtMwZm/OelOOnGxsa+7kLg"
    "gayXyRgpzDoEMaRzFc0oVFGECMxNHZVKQhTh0DNH2fvlvWCxbbFANGIWQAOmkYGfuIZX/nEP"
    "PfOuwlVSNJa4mmPxNb/2dQeMrXHp6xtdQssM7ZiZkXacezMiRmFK1pF4b0bZMVerYLNt3WMa"
    "Zg0NVBcMMH36MuKErHcQi9PkMAaMOWDm2+OX7t7lW3+bmtoCi/gYKVXpR6ibIGY01LgUI4Up"
    "U6qc855LITAjyrXvvAELTYg5Vkxi5RSUDfBtqw2lTOY5cWoCqao9+Z3TDy266bfuBqaTzjZf"
    "frrZOLGpVl816KTaNK2qaSzNomLRQTzmyxggBiMqFhuqMRWJtaHeuPkDPxsrAwPRk0Rfno3e"
    "WQxOo3cavWj0RYwnn305THk7d7LivrflNx/+FPAyEN/6F5IAPcAQP3L4+n8ZBowDLSB2b/4X"
    "JG61h+S4j6EAAAAASUVORK5CYII=")
getDzpkIconData = DzpkIcon.GetData
getDzpkIconImage = DzpkIcon.GetImage
getDzpkIconBitmap = DzpkIcon.GetBitmap

